version: '3.8'

services:
  syntactic-comparator:
    build:
      context: ./syntactic-comparator
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./syntactic-comparator:/app

  driver:
    build:
      context: ./driver
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    environment:
      - nlp_comparator_url=http://semantic-evaluator:4040
      - yamtl_comparator_url=http://syntactic-comparator:8080
    volumes:
      - ./driver:/driver

  semantic-evaluator:
    build:
      context: ./semantic-evaluator
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
    volumes:
      - ./semantic-evaluator:/app
