version: '3.8'

services:
  comparit-syntactic:
    image: jawad571/comparit-syntactic:v2.0.0
    ports:
      - "8080:8080"

  comparit-semantic:
    image: jawad571/comparit-semantic:1.0.0
    ports:
      - "9090:9090"
    environment:
      - EMBEDDING_MODEL=glove
  user-interface:
    image: jawad571/comparit-user-interface:1.0.0
    ports:
      - "8501:8501"
    environment:
      - COMPARIT_SYNTACTIC_URL=http://comparit-syntactic:8080
      - COMPARIT_SEMANTIC_URL=http://comparit-semantic:9090