<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EClass name="StanzaBuilder"/>
  <ecore:EClass name="PhoneNumber"/>
  <ecore:EClass name="KeyColor"/>
  <ecore:EClass name="CallFeatureDeviceKey"/>
  <ecore:EClass name="CallFeatureTextValue"/>
  <ecore:EClass name="ActiveFeature"/>
  <ecore:EClass name="HistoricalCall"/>
  <ecore:EClass name="CallFeatureHandset"/>
  <ecore:EClass name="OriginatorReference"/>
  <ecore:EClass name="DeviceKey"/>
  <ecore:EClass name="VoiceMessage"/>
  <ecore:EClass name="Site"/>
  <ecore:EClass name="DeviceStatus"/>
  <ecore:EClass name="RequestActionValue"/>
  <ecore:EClass name="RecorderPort"/>
  <ecore:EClass name="VoiceMessageFeature"/>
  <ecore:EClass name="InterestType"/>
  <ecore:EClass name="Interest"/>
  <ecore:EClass name="KeyPageModule"/>
  <ecore:EClass name="KeyLabel"/>
  <ecore:EClass name="CallFeatureBoolean"/>
  <ecore:EClass name="RecorderNumber"/>
  <ecore:EClass name="KeyModifier"/>
  <ecore:EClass name="KeyFunction"/>
  <ecore:EClass name="KeyId"/>
  <ecore:EClass name="FeatureId"/>
  <ecore:EClass name="PubSubNodeId"/>
  <ecore:EClass name="CallFeatureSpeakerChannel"/>
  <ecore:EClass name="ConferenceId"/>
  <ecore:EClass name="KeyQualifier"/>
  <ecore:EClass name="KeyPageLabel"/>
  <ecore:EClass name="CallFeature"/>
  <ecore:EClass name="KeyPageId"/>
  <ecore:EClass name="ItemId"/>
  <ecore:EClass name="Key"/>
  <ecore:EClass name="DeviceType"/>
  <ecore:EClass name="KeyPage"/>
  <ecore:EClass name="KeyPageLocalKeyPage"/>
  <ecore:EClass name="DeviceId"/>
  <ecore:EClass name="VoiceRecorderInfo"/>
  <ecore:EClass name="ProfileId"/>
  <ecore:EClass name="Participant"/>
  <ecore:EClass name="CallId"/>
  <ecore:EClass name="RecorderChannel"/>
  <ecore:EClass name="InterestId"/>
  <ecore:EClass name="UserId"/>
  <ecore:EClass name="MakeCallFeature"/>
  <ecore:EClass name="TelephonyCallId"/>
  <ecore:EClass name="KeyInterest"/>
  <ecore:EClass name="Call"/>
  <ecore:EClass name="RecorderType"/>
  <ecore:EClass name="AbstractType"/>
  <ecore:EClass name="Feature"/>
  <ecore:EClass name="CallFeatureVoiceRecorder"/>
  <ecore:EClass name="CallStatus"/>
  <ecore:EClass name="Profile"/>
  <ecore:EClass name="PubSubMessageBuilder"/>
  <ecore:EClass name="DeviceStatusMessageBuilder"/>
  <ecore:EClass name="CallStatusMessageBuilder"/>
  <ecore:EClass name="GetProfileRequestBuilder"/>
  <ecore:EClass name="PubSubPublishRequestBuilder"/>
  <ecore:EClass name="GetInterestsRequestBuilder"/>
  <ecore:EClass name="GetFeaturesResultBuilder"/>
  <ecore:EClass name="GetCallHistoryRequestBuilder"/>
  <ecore:EClass name="ManageVoiceMessageRequestBuilder"/>
  <ecore:EClass name="RequestActionRequestBuilder"/>
  <ecore:EClass name="GetProfileResultBuilder"/>
  <ecore:EClass name="PubSubSubscriptionRequestResultBuilder"/>
  <ecore:EClass name="IQBuilder"/>
  <ecore:EClass name="GetInterestResultBuilder"/>
  <ecore:EClass name="QueryFeaturesResultBuilder"/>
  <ecore:EClass name="GetCallHistoryResultBuilder"/>
  <ecore:EClass name="ManageVoiceMessageResultBuilder"/>
  <ecore:EClass name="SetFeaturesRequestBuilder"/>
  <ecore:EClass name="GetInterestRequestBuilder"/>
  <ecore:EClass name="GetProfilesRequestBuilder"/>
  <ecore:EClass name="GetFeaturesRequestBuilder"/>
  <ecore:EClass name="QueryFeaturesRequestBuilder"/>
  <ecore:EClass name="RequestActionResultBuilder"/>
  <ecore:EClass name="GetInterestsResultBuilder"/>
  <ecore:EClass name="MakeCallRequestBuilder"/>
  <ecore:EClass name="GetProfilesResultBuilder"/>
  <ecore:EClass name="MakeCallResultBuilder"/>
  <ecore:EClass name="J"/>
  <ecore:EClass name="Instant"/>
  <ecore:EClass name="Duration"/>
  <ecore:EClass name="Object"/>
  <ecore:EClass name="Serializable"/>
  <ecore:EClass name="Optional"/>
  <ecore:EClass name="Comparable_AbstractType_T__"/>
  <ecore:EClass name="T"/>
  <ecore:EClass name="List"/>
  <ecore:EClass name="Consumer"/>
  <ecore:EClass name="B"/>
  <ecore:EClass name="LocalDate"/>
</xmi:XMI>
