<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="default">
    <eClassifiers xsi:type="ecore:EClass" name="car">
      <eStructuralFeatures xsi:type="ecore:EReference" name="wheels" containment="true">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
	  </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="miles" containment="true">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
	  </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="lights" containment="true">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
	  </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="capacity" containment="true">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
	  </eStructuralFeatures>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
