<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="openlink" nsURI="http://yamtl.github.io/openlink" nsPrefix="openlink">
  <eClassifiers xsi:type="ecore:EClass" name="StanzaBuilder" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="//J"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="//J"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhoneNumber" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//PhoneNumber">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyColor" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//KeyColor">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallFeatureDeviceKey" eSuperTypes="//CallFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deviceKeys" upperBound="-1" eType="//DeviceKey"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallFeatureTextValue" eSuperTypes="//CallFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActiveFeature" eSuperTypes="//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value2">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value3">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HistoricalCall">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="//CallState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="//CallDirection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="callerName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="calledName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callId" eType="//CallId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userId" eType="//UserId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interestId" eType="//InterestId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callerNumber" eType="//PhoneNumber"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calledNumber" eType="//PhoneNumber"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startTime" eType="//Instant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duration" eType="//Duration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tsc" eType="//J"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallFeatureHandset" eSuperTypes="//CallFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="microphoneEnabled">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OriginatorReference">
    <eOperations name="equals">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="o">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="hashCode">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceKey" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//DeviceKey">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VoiceMessage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="//VoiceMessageStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="action" eType="//ManageVoiceMessageAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messageLength" eType="//Duration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="creationDate" eType="//Instant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extension" eType="//PhoneNumber"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Site" eSuperTypes="//Serializable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDefault">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceStatus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="online">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="profileId" eType="//ProfileId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deviceId" eType="//DeviceId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1" eType="//VoiceMessageFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequestActionValue" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//AbstractType">
      <eParameters name="type">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecorderPort" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//RecorderPort">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VoiceMessageFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureId" eType="//FeatureId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="voiceMessage" eType="//VoiceMessage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterestType" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//InterestType">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interest">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDefault">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxCalls">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interestId" eType="//InterestId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interestType" eType="//InterestType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callStatus" eType="//CallStatus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="number" eType="//PhoneNumber"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callForward" eType="//PhoneNumber"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyPageModule" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//KeyPageModule">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyLabel" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//KeyLabel">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallFeatureBoolean" eSuperTypes="//CallFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecorderNumber" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//RecorderNumber">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyModifier" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//KeyModifier">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyFunction" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//AbstractType">
      <eParameters name="type">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyId" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//KeyId">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureId" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//FeatureId">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PubSubNodeId" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//PubSubNodeId">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eOperations name="toInterestId" eType="//InterestId"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallFeatureSpeakerChannel" eSuperTypes="//CallFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="channel">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="microphoneActive">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="muteRequested">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConferenceId" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//ConferenceId">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyQualifier" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//KeyQualifier">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyPageLabel" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//KeyPageLabel">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallFeature" abstract="true" eSuperTypes="//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyPageId" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//KeyPageId">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItemId" eSuperTypes="//AbstractType">
    <eOperations name="random" eType="//ItemId"/>
    <eOperations name="from" eType="//ItemId">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Key">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="//KeyId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="//KeyLabel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="//KeyFunction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modifier" eType="//KeyModifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualifier" eType="//KeyQualifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="color" eType="//KeyColor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interest" eType="//KeyInterest"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceType" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//DeviceType">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyPage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyPageId" eType="//KeyPageId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyPageLabel" eType="//KeyPageLabel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyPageModule" eType="//KeyPageModule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localKeyPage" eType="//KeyPageLocalKeyPage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keys" upperBound="-1" eType="//Key"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyPageLocalKeyPage" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//KeyPageLocalKeyPage">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceId" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//DeviceId">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VoiceRecorderInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recorderNumber" eType="//RecorderNumber"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recorderPort" eType="//RecorderPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recorderChannel" eType="//RecorderChannel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recorderType" eType="//RecorderType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProfileId" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//ProfileId">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Participant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jid">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="participantType" eType="//ParticipantType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="participantCategory" eType="//ParticipantCategory"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="//CallDirection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="number" eType="//PhoneNumber"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="e164Numbers" upperBound="-1" eType="//PhoneNumber"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destinationNumber" eType="//PhoneNumber"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startTime" eType="//Instant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duration" eType="//Duration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallId" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//CallId">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecorderChannel" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//RecorderChannel">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterestId" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//InterestId">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eOperations name="toPubSubNodeId" eType="//PubSubNodeId"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserId" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//UserId">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MakeCallFeature">
    <eOperations name="stringToOptionalBoolean" eType="//Optional">
      <eParameters name="val1">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value2">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureId" eType="//FeatureId"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TelephonyCallId" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//TelephonyCallId">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyInterest" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//KeyInterest">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Call">
    <eOperations name="toCallStatus" eType="//CallStatus">
      <eParameters name="callStatusBusy">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changed" eType="//Changed"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="//CallState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="//CallDirection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="callerName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="calledName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actions" upperBound="-1" eType="//RequestAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callId" eType="//CallId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="telephonyCallId" eType="//TelephonyCallId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conferenceId" eType="//ConferenceId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="site" eType="//Site"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="profileId" eType="//ProfileId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deviceId" eType="//DeviceId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userId" eType="//UserId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interestId" eType="//InterestId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callerNumber" eType="//PhoneNumber"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callerE164Numbers" upperBound="-1" eType="//PhoneNumber"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calledNumber" eType="//PhoneNumber"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calledDestination" eType="//PhoneNumber"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calledE164Numbers" upperBound="-1" eType="//PhoneNumber"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="originatorReferences" upperBound="-1" eType="//OriginatorReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startTime" eType="//Instant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duration" eType="//Duration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1" eType="//CallFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participants" upperBound="-1" eType="//Participant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecorderType" eSuperTypes="//AbstractType">
    <eOperations name="from" eType="//RecorderType">
      <eParameters name="type" eType="//AbstractType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractType" abstract="true" eSuperTypes="//Serializable //Comparable_AbstractType_T__">
    <eOperations name="equals">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="o">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eParameters>
    </eOperations>
    <eOperations name="hashCode">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="compareTo">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="that" eType="//AbstractType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="//T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureType" eType="//FeatureType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureId" eType="//FeatureId"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallFeatureVoiceRecorder" eSuperTypes="//CallFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="voiceRecorderInfo" eType="//VoiceRecorderInfo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallStatus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="callStatusBusy">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callForward" eType="//PhoneNumber"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calls" upperBound="-1" eType="//Call"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Profile" eSuperTypes="//Serializable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDefault">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="online">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="profileId" eType="//ProfileId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deviceType" eType="//DeviceType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deviceId" eType="//DeviceId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="site" eType="//Site"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyPages" upperBound="-1" eType="//KeyPage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1" eType="//List"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PubSubMessageBuilder" abstract="true" eSuperTypes="//StanzaBuilder">
    <eOperations name="validate">
      <eParameters name="errors" upperBound="-1" eType="//List"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="delay" eType="//Instant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pubSubNodeId" eType="//PubSubNodeId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="itemId" eType="//ItemId"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceStatusMessageBuilder" abstract="true" eSuperTypes="//PubSubMessageBuilder">
    <eOperations name="validate">
      <eParameters name="errors" upperBound="-1" eType="//List"/>
      <eParameters name="checkIQFields">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deviceStatus" eType="//DeviceStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallStatusMessageBuilder" abstract="true" eSuperTypes="//PubSubMessageBuilder">
    <eOperations name="validate">
      <eParameters name="errors" upperBound="-1" eType="//List"/>
    </eOperations>
    <eOperations name="validateCallsAreOnTheCorrectInterest">
      <eParameters name="callStatus" eType="//CallStatus"/>
      <eParameters name="errorConsumer" eType="//Consumer"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callStatus" eType="//CallStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetProfileRequestBuilder" abstract="true" eSuperTypes="//IQBuilder">
    <eOperations name="validate">
      <eParameters name="errors" upperBound="-1" eType="//List"/>
      <eParameters name="checkIQFields">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="profileId" eType="//ProfileId"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PubSubPublishRequestBuilder" abstract="true" eSuperTypes="//IQBuilder">
    <eOperations name="validate">
      <eParameters name="errors" upperBound="-1" eType="//List"/>
      <eParameters name="checkIQFields">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eParameters>
    </eOperations>
    <eOperations name="validateCallsAreOnTheCorrectInterest">
      <eParameters name="callStatus" eType="//CallStatus"/>
      <eParameters name="errorConsumer" eType="//Consumer"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pubSubNodeId" eType="//PubSubNodeId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callStatus" eType="//CallStatus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deviceStatus" eType="//DeviceStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetInterestsRequestBuilder" abstract="true" eSuperTypes="//IQBuilder">
    <eOperations name="validate">
      <eParameters name="errors" upperBound="-1" eType="//List"/>
      <eParameters name="checkIQFields">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="profileId" eType="//ProfileId"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetFeaturesResultBuilder" abstract="true" eSuperTypes="//IQBuilder">
    <eOperations name="addFeature" eType="//B">
      <eParameters name="feature" eType="//Feature"/>
    </eOperations>
    <eOperations name="validate">
      <eParameters name="errors" upperBound="-1" eType="//List"/>
      <eParameters name="checkIQFields">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eParameters>
    </eOperations>
    <eOperations name="validateUniqueness">
      <eParameters name="errorConsumer" eType="//Consumer"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="profileId" eType="//ProfileId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1" eType="//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetCallHistoryRequestBuilder" abstract="true" eSuperTypes="//IQBuilder">
    <eOperations name="validate">
      <eParameters name="errors" upperBound="-1" eType="//List"/>
      <eParameters name="checkIQFields">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="caller">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="called">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="callType" eType="//CallType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jid" eType="//J"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromDate" eType="//LocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upToDate" eType="//LocalDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ManageVoiceMessageRequestBuilder" abstract="true" eSuperTypes="//IQBuilder">
    <eOperations name="validate">
      <eParameters name="errors" upperBound="-1" eType="//List"/>
      <eParameters name="checkIQFields">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eParameters>
    </eOperations>
    <eOperations name="addFeature" eType="//B">
      <eParameters name="feature" eType="//FeatureId"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="action" eType="//ManageVoiceMessageAction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="profileId" eType="//ProfileId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1" eType="//FeatureId"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequestActionRequestBuilder" abstract="true" eSuperTypes="//IQBuilder">
    <eOperations name="addFeatures" eType="//B">
      <eParameters name="features" upperBound="-1" eType="//List"/>
    </eOperations>
    <eOperations name="addFeature" eType="//B">
      <eParameters name="feature" eType="//MakeCallFeature"/>
    </eOperations>
    <eOperations name="validate">
      <eParameters name="errors" upperBound="-1" eType="//List"/>
      <eParameters name="checkIQFields">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eParameters>
    </eOperations>
    <eOperations name="checkValuesArePResent">
      <eParameters name="requestActionToCheck" eType="//RequestAction"/>
      <eParameters name="errors" upperBound="-1" eType="//List"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestAction" eType="//RequestAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interestId" eType="//InterestId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callId" eType="//CallId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value2" eType="//RequestActionValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value1" eType="//RequestActionValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1" eType="//MakeCallFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetProfileResultBuilder" abstract="true" eSuperTypes="//IQBuilder">
    <eOperations name="validate">
      <eParameters name="errors" upperBound="-1" eType="//List"/>
      <eParameters name="checkIQFields">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="profile" eType="//Profile"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PubSubSubscriptionRequestResultBuilder" abstract="true" eSuperTypes="//IQBuilder">
    <eOperations name="validate">
      <eParameters name="errors" upperBound="-1" eType="//List"/>
      <eParameters name="checkIQFields">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subscriptionState" eType="//SubscriptionState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pubSubNodeId" eType="//PubSubNodeId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jid" eType="//J"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IQBuilder" abstract="true" eSuperTypes="//StanzaBuilder">
    <eOperations name="validate">
      <eParameters name="errors" upperBound="-1" eType="//List"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iqType" eType="//T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetInterestResultBuilder" abstract="true" eSuperTypes="//IQBuilder">
    <eOperations name="validate">
      <eParameters name="errors" upperBound="-1" eType="//List"/>
      <eParameters name="checkIQFields">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interest" eType="//Interest"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryFeaturesResultBuilder" abstract="true" eSuperTypes="//IQBuilder">
    <eOperations name="addFeature" eType="//B">
      <eParameters name="feature" eType="//ActiveFeature"/>
    </eOperations>
    <eOperations name="validate">
      <eParameters name="errors" upperBound="-1" eType="//List"/>
      <eParameters name="checkIQFields">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1" eType="//ActiveFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetCallHistoryResultBuilder" abstract="true" eSuperTypes="//IQBuilder">
    <eOperations name="addCall" eType="//B">
      <eParameters name="call" eType="//HistoricalCall"/>
    </eOperations>
    <eOperations name="addCalls" eType="//B">
      <eParameters name="calls" upperBound="-1" eType="//List"/>
    </eOperations>
    <eOperations name="validate">
      <eParameters name="errors" eType="//List"/>
      <eParameters name="checkIQFields">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalRecordCount">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstRecordNumber">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recordCountInBatch">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calls" upperBound="-1" eType="//HistoricalCall"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ManageVoiceMessageResultBuilder" eSuperTypes="//IQBuilder">
    <eOperations name="validate">
      <eParameters name="errors" upperBound="-1" eType="//List"/>
      <eParameters name="checkIQFields">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deviceStatus" eType="//DeviceStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetFeaturesRequestBuilder" eSuperTypes="//IQBuilder">
    <eOperations name="validate">
      <eParameters name="errors" upperBound="-1" eType="//List"/>
      <eParameters name="checkIQFields">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value2">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value3">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="profileId" eType="//ProfileId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureId" eType="//FeatureId"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetInterestRequestBuilder" abstract="true" eSuperTypes="//IQBuilder">
    <eOperations name="validate">
      <eParameters name="errors" upperBound="-1" eType="//List"/>
      <eParameters name="checkIQFields">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interestId" eType="//InterestId"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetProfilesRequestBuilder" abstract="true" eSuperTypes="//IQBuilder">
    <eOperations name="validate">
      <eParameters name="errors" upperBound="-1" eType="//List"/>
      <eParameters name="checkIQFields">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jid" eType="//J"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetFeaturesRequestBuilder" abstract="true" eSuperTypes="//IQBuilder">
    <eOperations name="validate">
      <eParameters name="errors" upperBound="-1" eType="//List"/>
      <eParameters name="checkIQFields">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="profileId" eType="//ProfileId"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryFeaturesRequestBuilder" eSuperTypes="//IQBuilder">
    <eOperations name="validate">
      <eParameters name="errors" upperBound="-1" eType="//List"/>
      <eParameters name="checkIQFields">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="profileId" eType="//ProfileId"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequestActionResultBuilder" abstract="true" eSuperTypes="//IQBuilder //B //J //T">
    <eOperations name="validate">
      <eParameters name="errors" upperBound="-1" eType="//List"/>
      <eParameters name="checkIQFields">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callStatus" eType="//CallStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetInterestsResultBuilder" abstract="true" eSuperTypes="//IQBuilder">
    <eOperations name="addInterest" eType="//B">
      <eParameters name="interest" eType="//Interest"/>
    </eOperations>
    <eOperations name="validate">
      <eParameters name="errors" upperBound="-1" eType="//List"/>
      <eParameters name="checkIQFields">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eParameters>
    </eOperations>
    <eOperations name="validateUniqueness">
      <eParameters name="errorConsumer" eType="//Consumer"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interests" upperBound="-1" eType="//Interest"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MakeCallRequestBuilder" abstract="true" eSuperTypes="//IQBuilder">
    <eOperations name="addFeature" eType="//B">
      <eParameters name="feature" eType="//MakeCallFeature"/>
    </eOperations>
    <eOperations name="addOriginatorReference" eType="//B">
      <eParameters name="originatorReference" eType="//OriginatorReference"/>
    </eOperations>
    <eOperations name="validate">
      <eParameters name="errors" upperBound="-1" eType="//List"/>
      <eParameters name="checkIQFields">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jid" eType="//J"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="profileId" eType="//ProfileId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interestId" eType="//InterestId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" eType="//PhoneNumber"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1" eType="//MakeCallFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="originatorReferences" upperBound="-1" eType="//OriginatorReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetProfilesResultBuilder" abstract="true" eSuperTypes="//IQBuilder">
    <eOperations name="addProfile" eType="//B">
      <eParameters name="profile" eType="//Profile"/>
    </eOperations>
    <eOperations name="validate">
      <eParameters name="errors" upperBound="-1" eType="//List"/>
      <eParameters name="checkIQFields">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eParameters>
    </eOperations>
    <eOperations name="validateUniqueness">
      <eParameters name="errorConsumer" eType="//Consumer"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="profiles" upperBound="-1" eType="//Profile"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MakeCallResultBuilder" abstract="true" eSuperTypes="//IQBuilder">
    <eOperations name="validate">
      <eParameters name="errors" upperBound="-1" eType="//List"/>
      <eParameters name="checkIQFields">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callStatus" eType="//CallStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="J" abstract="true">
    <eAnnotations source="dependency"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instant" abstract="true">
    <eAnnotations source="dependency"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Duration" abstract="true">
    <eAnnotations source="dependency"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object" abstract="true">
    <eAnnotations source="dependency"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Serializable" abstract="true" interface="true">
    <eAnnotations source="dependency"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Optional" abstract="true">
    <eAnnotations source="dependency"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comparable_AbstractType_T__" abstract="true" interface="true">
    <eAnnotations source="dependency"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="T" abstract="true" interface="true">
    <eAnnotations source="dependency"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="List" abstract="true">
    <eAnnotations source="dependency"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Consumer" abstract="true">
    <eAnnotations source="dependency"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="B" abstract="true">
    <eAnnotations source="dependency"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalDate" abstract="true">
    <eAnnotations source="dependency"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OpenlinkXmppNamespace">
    <eLiterals name="XMPP_PUBSUB"/>
    <eLiterals name="XMPP_PUBSUB_EVENT" value="1"/>
    <eLiterals name="XMPP_DISCO_INFO" value="2"/>
    <eLiterals name="XMPP_DISCO_ITEMS" value="3"/>
    <eLiterals name="XMPP_COMMANDS" value="4"/>
    <eLiterals name="XMPP_IO_DATA" value="5"/>
    <eLiterals name="OPENLINK_GET_PROFILES" value="6"/>
    <eLiterals name="OPENLINK_GET_PROFILE" value="7"/>
    <eLiterals name="OPENLINK_PROFILES" value="8"/>
    <eLiterals name="OPENLINK_PROFILE" value="9"/>
    <eLiterals name="OPENLINK_GET_INTERESTS" value="10"/>
    <eLiterals name="OPENLINK_GET_INTEREST" value="11"/>
    <eLiterals name="OPENLINK_INTERESTS" value="12"/>
    <eLiterals name="OPENLINK_GET_FEATURES" value="13"/>
    <eLiterals name="OPENLINK_FEATURES" value="14"/>
    <eLiterals name="OPENLINK_MAKE_CALL" value="15"/>
    <eLiterals name="OPENLINK_REQUEST_ACTION" value="16"/>
    <eLiterals name="OPENLINK_MAKE_INTERCOM_CALL" value="17"/>
    <eLiterals name="OPENLINK_MANAGE_VOICE_MESSAGE" value="18"/>
    <eLiterals name="OPENLINK_VOICE_MESSAGE" value="19"/>
    <eLiterals name="OPENLINK_MANAGE_VOICE_BLAST" value="20"/>
    <eLiterals name="OPENLINK_MANAGE_VOICE_BRIDGE" value="21"/>
    <eLiterals name="OPENLINK_MANAGE_INTERESTS" value="22"/>
    <eLiterals name="OPENLINK_SET_FEATURES" value="23"/>
    <eLiterals name="OPENLINK_QUERY_FEATURES" value="24"/>
    <eLiterals name="OPENLINK_GET_CALL_HISTORY" value="25"/>
    <eLiterals name="OPENLINK_CALL_STATUS" value="26"/>
    <eLiterals name="OPENLINK_DEVICE_STATUS" value="27"/>
    <eLiterals name="OPENLINK_DEVICE_KEY" value="28"/>
    <eLiterals name="OPENLINK_SPEAKER_CHANNEL" value="29"/>
    <eLiterals name="OPENLINK_VOICE_RECORDER" value="30"/>
    <eLiterals name="OPENLINK_CALL_HISTORY" value="31"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParticipantType">
    <eLiterals name="Active"/>
    <eLiterals name="Alerting" value="1"/>
    <eLiterals name="Inactive" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VoiceMessageStatus">
    <eLiterals name="OK"/>
    <eLiterals name="ERROR" value="1"/>
    <eLiterals name="WARN" value="2"/>
    <eLiterals name="UNKNOWN" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ManageVoiceMessageAction">
    <eLiterals name="CREATE"/>
    <eLiterals name="RECORD" value="1"/>
    <eLiterals name="EDIT" value="2"/>
    <eLiterals name="PLAYBACK" value="3"/>
    <eLiterals name="SAVE" value="4"/>
    <eLiterals name="ARCHIVE" value="5"/>
    <eLiterals name="DELETE" value="6"/>
    <eLiterals name="QUERY" value="7"/>
    <eLiterals name="SEARCH" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FeatureType">
    <eLiterals name="MESSAGE_WAITING"/>
    <eLiterals name="MICROPHONE_GAIN" value="1"/>
    <eLiterals name="MICROPHONE_MUTE" value="2"/>
    <eLiterals name="RINGER_STATUS" value="3"/>
    <eLiterals name="SPEAKER_MUTE" value="4"/>
    <eLiterals name="SPEED_DIAL" value="5"/>
    <eLiterals name="GROUP_INTERCOM" value="6"/>
    <eLiterals name="SPEAKER_CHANNEL" value="7"/>
    <eLiterals name="VOICE_MESSAGE" value="8"/>
    <eLiterals name="VOICE_MESSAGE_PLAYLIST" value="9"/>
    <eLiterals name="VOICE_RECORDER" value="10"/>
    <eLiterals name="VOICE_BRIDGE" value="11"/>
    <eLiterals name="PRIVACY" value="12"/>
    <eLiterals name="HANDSET" value="13"/>
    <eLiterals name="HEADSET" value="14"/>
    <eLiterals name="DO_NOT_DISTURN" value="15"/>
    <eLiterals name="CALL_FORWARD" value="16"/>
    <eLiterals name="CALL_BACK" value="17"/>
    <eLiterals name="CONFERENCE" value="18"/>
    <eLiterals name="MEDIA_STREAM" value="19"/>
    <eLiterals name="DEVICE_KEYS" value="20"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CallType">
    <eLiterals name="INBOUND"/>
    <eLiterals name="OUTBOUND" value="1"/>
    <eLiterals name="MISSED" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SubscriptionState">
    <eLiterals name="NONE"/>
    <eLiterals name="PENDING" value="1"/>
    <eLiterals name="UNCONFIGURED" value="2"/>
    <eLiterals name="SUBSCRIBED" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RequestAction">
    <eLiterals name="ANSWER_CALL"/>
    <eLiterals name="HOLD_CALL" value="1"/>
    <eLiterals name="INTERCOM_TRANSFER" value="2"/>
    <eLiterals name="JOIN_CALL" value="3"/>
    <eLiterals name="RETRIEVE_CALL" value="4"/>
    <eLiterals name="CONSULTATION_CALL" value="5"/>
    <eLiterals name="TRANSFER_CALL" value="6"/>
    <eLiterals name="CONFERENCE_CALL" value="7"/>
    <eLiterals name="SINGLE_STEP_TRANSFER" value="8"/>
    <eLiterals name="SEND_DIGIT" value="9"/>
    <eLiterals name="SEND_DIGITS" value="10"/>
    <eLiterals name="CLEAR_CONFERENCE" value="11"/>
    <eLiterals name="CLEAR_CONNECTION" value="12"/>
    <eLiterals name="CLEAR_CALL" value="13"/>
    <eLiterals name="START_VOICE_DROP" value="14"/>
    <eLiterals name="STOP_VOICE_DROP" value="15"/>
    <eLiterals name="PRIVATE_CALL" value="16"/>
    <eLiterals name="PUBLIC_CALL" value="17"/>
    <eLiterals name="ADD_THIRD_PARTY" value="18"/>
    <eLiterals name="REMOVE_THIRD_PARTY" value="19"/>
    <eLiterals name="CONNECT_SPEAKER" value="20"/>
    <eLiterals name="DISCONNECT_SPEAKER" value="21"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Changed">
    <eLiterals name="STATE"/>
    <eLiterals name="ACTIONS" value="1"/>
    <eLiterals name="PARTICIPANT" value="2"/>
    <eLiterals name="CALLER" value="3"/>
    <eLiterals name="CALLED" value="4"/>
    <eLiterals name="PRIVACY" value="5"/>
    <eLiterals name="VOICE_MESSAGE" value="6"/>
    <eLiterals name="MICROPHONE" value="7"/>
    <eLiterals name="HANDSET" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CallState">
    <eLiterals name="CALL_ORIGINATED"/>
    <eLiterals name="CALL_DELIVERED" value="1"/>
    <eLiterals name="CALL_ESTABLISHED" value="2"/>
    <eLiterals name="CALL_FAILED" value="3"/>
    <eLiterals name="CALL_CONFERENCED" value="4"/>
    <eLiterals name="CALL_BUSY" value="5"/>
    <eLiterals name="CALL_HELD" value="6"/>
    <eLiterals name="CALL_HELD_ELSEWHERE" value="7"/>
    <eLiterals name="CALL_TRANSFERRING" value="8"/>
    <eLiterals name="CALL_TRANSFERRED" value="9"/>
    <eLiterals name="TRANSFER_COMPLETED" value="10"/>
    <eLiterals name="CONNECTION_BUSY" value="11"/>
    <eLiterals name="CONNECTION_CLEARED" value="12"/>
    <eLiterals name="CALL_MISSED" value="13"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParticipantCategory">
    <eLiterals name="CONF"/>
    <eLiterals name="ADD3P" value="1"/>
    <eLiterals name="BARGE" value="2"/>
    <eLiterals name="VOICE_DROP" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CallDirection">
    <eLiterals name="Outgoing"/>
    <eLiterals name="Incoming" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Type">
    <eLiterals name="Avaya"/>
    <eLiterals name="BTSM" value="1"/>
    <eLiterals name="Cisco" value="2"/>
    <eLiterals name="IPT" value="3"/>
    <eLiterals name="ITS" value="4"/>
  </eClassifiers>
</ecore:EPackage>
