<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="vjava" nsURI="http://yamtl.github.io/vjava" nsPrefix="vjava">
  <eClassifiers xsi:type="ecore:EClass" name="ReponseT" eSuperTypes="//Reponse"/>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="greetings" upperBound="-1" eType="//Greeting"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reponse">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReponseF" eSuperTypes="//Reponse"/>
  <eClassifiers xsi:type="ecore:EClass" name="Greeting">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="question">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reponses" upperBound="-1" eType="//Reponse"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Features">
    <eOperations name="basicGetType" eType="//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1" eType="//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="//Type">
    <eOperations name="basicGetSupertype" eType="//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supertype" eType="//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1" eType="//Features" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
