@startuml
package app.controllers {
	class semantic_similarity_controller {

	}
}

package app.services {
	class semantic_similarity_service {
		+ compare_emfatic_files(base_emfatic_file, predicted_emfatic_file, model)
		+ get_weighted_embeddings(doc, tfidf_weights)
		+ get_tokens(text)
		+ extract_comments_and_names(text)
	}
}

semantic_similarity_controller "1" *--> "1" semantic_similarity_service: uses
@enduml