@startuml
left to right direction
actor "User" as fc
rectangle Comparit-User-Interface{
  usecase "Input pair of Ecore Models" as UC1
  usecase "Specify Configuration" as UC2
  usecase "View Comparison Results" as UC3
}

fc --> UC1
fc --> UC2
fc --> UC3
@enduml