<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ECommerceBackend" nsURI="https://github.com/MET-DEV/E-Commerce-Backend" nsPrefix="E-Commerce-Backend">
  <eClassifiers xsi:type="ecore:EClass" name="CategoriesController">
    <eOperations name="getCategories" upperBound="-1" eType="//Category"/>
    <eOperations name="getCategoryById" eType="//ResponseEntity">
      <eParameters name="_id">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
    <eOperations name="SaveCategory" eType="//ResponseEntity">
      <eParameters name="category" eType="//Category"/>
    </eOperations>
    <eOperations name="updateCategory" eType="//ResponseEntity">
      <eParameters name="category" eType="//Category"/>
    </eOperations>
    <eOperations name="deleteCategory" eType="//ResponseEntity">
      <eParameters name="category" eType="//Category"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categoryRepository" lowerBound="1" eType="//CategoryRepository"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrdersController">
    <eOperations name="getAll" upperBound="-1" eType="//Order"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orderRepository" lowerBound="1" eType="//OrderRepository"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductMutationResolver" eSuperTypes="//GraphQLMutationResolver">
    <eOperations name="saveProduct" eType="//Product">
      <eParameters name="product" eType="//Product"/>
    </eOperations>
    <eOperations name="updateProduct" eType="//Product">
      <eParameters name="product" eType="//Product"/>
    </eOperations>
    <eOperations name="deleteProduct">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="_id">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="productRepository" lowerBound="1" eType="//ProductRepository"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductQueryResolver" eSuperTypes="//GraphQLQueryResolver">
    <eOperations name="getProducts" upperBound="-1" eType="//Product"/>
    <eOperations name="getProductById" eType="//Product"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="productRepository" lowerBound="1" eType="//ProductRepository"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Category">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="_id">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="categoryName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="products" upperBound="-1" eType="//Product"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Order">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="_id">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationDate">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="products" upperBound="-1" eType="//Product"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="_id">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="productName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="createDate">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="category" eType="//Category"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orderItems" upperBound="-1" eType="//Order"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CategoryRepository" eSuperTypes="//JpaRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Category" upperBound="-1" eType="//Category"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrderRepository" eSuperTypes="//JpaRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Order" upperBound="-1" eType="//Order"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductRepository" eSuperTypes="//JpaRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="product" upperBound="-1" eType="//Product"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphQLMutationResolver"/>
  <eClassifiers xsi:type="ecore:EClass" name="JpaRepository"/>
  <eClassifiers xsi:type="ecore:EClass" name="GraphQLQueryResolver"/>
</ecore:EPackage>
